---
- name: Wait for 15 seconds to allow the update process to start
  pause:
    seconds 15

- name: Check the worker nodes managed by MCP are updated and ready
  k8s_info:
    kind: MachineConfigPool
    name: worker
  register: mcp_worker
  retries: 150
  delay: 10
  until:
    - "mcp_worker.resources|length == 1"
    - "'status' in mcp_worker.resources[0]"
    - "mcp_worker.resources[0].status.readyMachineCount == mcp_worker.resources[0].status.updatedMachineCount"

- name: Check all nodes are in schedulable state
  k8s_info:
    kind: Node
    field_selectors:
      - spec.unschedulable=true
  register: nodes
  retries: 150
  delay: 10
  until: "'resources' in nodes and nodes.resources|length == 0"
  failed_when: "'resources' not in nodes or nodes.resources|length != 0"
